### ISSUE TITLE
In the context memory unit, what are the assumptions for value generation?

### ISSUE THREAD

**Issue by Doloxetine** [facebookresearch/MemoryMosaics#4]
为什么t时刻的value会依赖于t+1时刻的输入？value的含义是什么？这是否会破坏因果性？

Why does the value at time 𝑡 depend on the input at time 𝑡+1 ? What‘s  the meaning of value? Does this breaks down causality?

**Comment by niklasnolte** [comment]
It does not break down causality if the attention mask excludes the main diagonal. The value at the current time T is what the CMem tries to approximate via the history (context). Because v_t is a function of x_{t+1} and k_t is a function of x_t, the CMem creates an associative memory that associates some time step t to its immediate future t+1. Via a new query (==key) you can get an averaged approximation of the new value (via kernel smoothing). You could maybe see how this makes it easy to build an induction head. More details in Section 2 of the paper: "Predicting with associative Memories"
